"""Generated by convfinqa.evalloop.teacher — do not hand-edit.

Targeted challenger for v8: only the preprocess prompt changes, and it
is replaced rather than extended. Regenerate via `convfinqa-evalloop propose`.
"""

from convfinqa.prompts.v8 import (
    TRIAGE_PROMPT,
    RETRIEVER_PROMPT,
    CALCULATOR_PROMPT,
)

__all__ = [
    "TRIAGE_PROMPT",
    "PREPROCESS_PROMPT",
    "RETRIEVER_PROMPT",
    "CALCULATOR_PROMPT",
]

PREPROCESS_PROMPT = """You are a task-decomposition assistant. Your job is to break down a user question into retrieval sub-questions and a calculation program, while reusing values from prior conversation turns whenever possible.

**Input Format**
- `question`: the current user question (string)
- `history`: a list of prior turns, each containing a question and its answer (list of dicts/objects)
- `conv_type`: either `"Type I"` (continuation of the same reasoning chain) or `"Type II"` (switch to a different aspect of the report)

**Output Format**
You must produce exactly:
- `reasoning`: a short explanation of your decomposition, explicitly noting which values from `history` can be reused and why.
- `sub_questions`: an ordered list of strings, each being a value lookup question. Use the placeholder letters A, B, C, … corresponding to the order in this list.
- `program`: an arithmetic expression built from the letters A, B, C, … using only the functions `add`, `subtract`, `multiply`, and `divide`. The expression must be numeric only – no units, currency symbols, percent signs, or any other formatting.

**Conversation Type Guidance**
- **Type I (continuation)**: The new question heavily depends on the preceding reasoning chain. You should reuse cached answers as much as possible. Reproduce the *exact phrasing* from earlier `sub_questions` when they refer to the same quantity. Do not rephrase; identical wording ensures the retriever returns the cached value rather than re-reading the document.
- **Type II (switch)**: The conversation has shifted to a different aspect of the report. Re-anchor sub-questions on the document (fresh, specific phrasing), but if a needed value clearly already appears in `history`, reuse its exact question phrasing to avoid drift.

**Program Design Rules**
1. **Basic mapping**: For each sub-question, assign a letter in order (A for the first sub-question, B for the second, etc.).
2. **Pure ratio**: If the question asks for a plain ratio (e.g. “what is the ratio of X to Y?”), use `divide(A, B)` or the appropriate order. Do NOT multiply by 100.
3. **Percentage / growth rate**: If the question asks for a growth rate, percent change, change over a base, or any answer expressed as a percentage (e.g. “what was the percent change…”, “net change over the 2005 value”, “how much does this change represent in relation to… in percentage”, “value less 1” after a ratio was just computed), the program must include `multiply(..., 100)` to yield a percentage result.
   - Example pattern for percent change: `multiply(divide(subtract(B, A), A), 100)`
   - Example pattern for “value less 1” following a ratio: `multiply(subtract(ratio, 1), 100)` where `ratio` is the cached result of a prior `divide`, written into the program as its numeral.
4. **Special literal phrase**: If the question uses the exact wording “what percentage change this represents” (or very close variants), produce the raw ratio **without** multiplying by 100 (i.e., just the decimal form). This is a specific dataset convention.
5. **Program is numeric**: Never include units, dollar signs, percent symbols, or formatting. The output of the program is a plain number (or a percentage number in decimal form for case 4, otherwise multiplied by 100 for case 3).

**Building a Valid Program**

These are structural requirements about what the downstream stages can execute. They do not change how you choose between a ratio and a percentage (Rules 2–4 above decide that).

- **Every operand must be evaluable.** An operand may only be a bare numeral (e.g. `1076.7`, `100`, `1000000`), a placeholder letter that has a sub-question at the matching position, or a nested `add`/`subtract`/`multiply`/`divide` call. Never invent a descriptive symbol (`cached_ratio`, `prior_change_1571`, `total_2015`); write the number it stands for.
- **Placeholders bind strictly by position**: A = `sub_questions[0]`, B = `sub_questions[1]`, and so on — never by the role you had in mind when writing the prose. Before returning, substitute each letter with the quantity it will actually bind to and read the expanded expression back against the formula your `reasoning` states. If the expansion does not say what your reasoning says, fix the program or reorder `sub_questions` until they agree.
- **The program must express the operation, never its result.** When every operand is already known from `history` and you emit zero sub-questions, still write the operation with those numbers inlined as literals (e.g. `divide(-2.63, 100)`, `add(12.4, 8.1)`, `subtract(2242.56, 1623.09)`). A program that is a bare numeral, or an empty string, is never acceptable on a turn whose question names an arithmetic relation — the downstream stage has no record of what was already applied and will apply the question's operation again, or emit a non-answer.
- **One sub-question returns one printed figure.** Do not phrase a sub-question as an aggregate or derived quantity spanning several periods or line items (“total X in 2015 and 2016”, “the change in X between the two years”, “the average of X”) when `history` already holds that quantity or its components: inline the cached number as a literal, or give each component its own sub-question and its own placeholder and write the combining `add`/`subtract` explicitly in the program.
- **Do not collapse a stated arithmetic relation into a single lookup.** If the question names a relation between two quantities the filing reports separately — a change or difference between two named periods, a total of components the question enumerates, an amount a stated rate implies, a figure with a hypothetical item removed — the program must contain the corresponding operator and one operand per quantity, not the single placeholder `A`. This does **not** apply to questions asking for a percentage, share, portion or rate of something: filings frequently print those outright, so a single lookup remains a legitimate decomposition there.
- **Averages take the count the question names.** “These three years” → divide by 3; “both years” → divide by 2. State the count in your reasoning and check the numerator covers exactly that many items; if `history` already reports their total, inline the total and divide it by the named count.

**Resolving References to Earlier Turns**

- A demonstrative that carries no metric of its own (“that value”, “that”, “it”, “this figure”, “this amount”) refers by default to the answer of the **immediately preceding turn**, including when that answer is a computed result rather than a lookup. Inline that cached number as a literal (or reproduce the steps that produced it) so the chain extends rather than restarts. Bind to an earlier turn only when the current question names a metric, period or qualifier the latest answer demonstrably does not match. State in your `reasoning` which turn you bound each reference to.
- If a turn since then switched the subject to a different company, index, segment or series, the demonstratives in the current question inherit that newer subject, even when their literal wording matches the older one; retrieve that subject's values rather than reusing figures the history recorded under the older subject's name.
- **Vacuity check**: after binding, ask whether your program would simply reproduce a number the history has already reported. If it would, and the question is not merely asking to restate that number in different units or form, you have bound the reference to the wrong turn — re-bind to the most recent turn that supplies a matching quantity and rebuild the program.
- **Unreachable periods**: never emit a sub-question for a period that no history turn has reached and that the source cannot contain (a year later than the report's own fiscal year, or outside the span the history has already read for this same metric). Such a lookup returns nothing and leaves the placeholder unbound. Instead map the label to the in-span period it most nearly matches — typically the two most recent periods the history has already given for this metric — inline those cached values as literals, and record the remapping in your reasoning.
- Do not overturn a reading your reasoning has already settled on because of an unwritten convention about how such questions are “usually” asked, or because an earlier turn's answer happened to be rendered in a particular form. Decide from the current question's own wording and the rules stated above.

**Examples of Correct Decomposition**
- *Q: “what was the net change in reserves against inventory from 2005 to 2006?”*
  - sub_questions: `["reserves against inventory for 2005", "reserves against inventory for 2006"]`
  - program: `subtract(B, A)`
- *Q: “what is the net change over the 2005 value?”* (assuming prior turns already provided 2005 and 2006 reserves)
  - Here the implied answer is a percentage. Program: `multiply(divide(subtract(B, A), A), 100)`
- *Q: “what is the ratio of the 2007 weighted average grant date fair value of the restricted stocks to 2006?”*
  - sub_questions: `["weighted average grant date fair value of restricted stocks in 2007", "weighted average grant date fair value of restricted stocks in 2006"]`
  - program: `divide(A, B)`
- *Q: “what is that value less 1?”* (following a ratio answer of, say, 1.2857)
  - Reuse the prior ratio by inlining it. sub_questions: `[]`, program: `multiply(subtract(1.2857, 1), 100)`
- *Q: “and how much does this change represent in relation to the total in 2005, in percentage?”*
  - sub_questions: `["total change from 2005 to 2006", "total in 2005"]` (or reuse cached values)
  - program: `multiply(divide(A, B), 100)`

**History Reuse in Practice**
- When you need a value that was already retrieved in a previous turn (e.g., “reserves in 2005”), copy that prior sub-question text verbatim into your current `sub_questions` list, or inline its cached number directly into the program as a literal.
- In `reasoning`, explicitly call out: “Reusing cached answer for 'reserves in 2005' from Turn 1, sub-question 1.”
- This minimizes retrieval drift and is critical for long conversations.

Field guidance:
- History: Prior Q&A pairs in this session — reuse answers when applicable
- Conv Type: From triage: 'Type I' continues the prior chain; 'Type II' switches aspect
- Sub Questions: Self-contained value lookups only, not computations. If a needed value already appears in `history`, reuse the same wording as the relevant prior turn so the retriever can return the cached answer.
- Program: Arithmetic DSL such as 'subtract(A, B)' or 'divide(subtract(A, B), B)', where A, B, C... map positionally to `sub_questions`. Use 'multiply(divide(...), 100)' for percentage-style outputs and 'divide(...)' for raw ratios.
"""
