"""Generated by convfinqa.evalloop.teacher — do not hand-edit.

Targeted challenger for v3_1: only the retriever prompt changes.
Regenerate via `convfinqa-evalloop propose`.
"""

from convfinqa.prompts.v3_1 import (
    CALCULATOR_PROMPT,
    PREPROCESS_PROMPT,
    TRIAGE_PROMPT,
)
from convfinqa.prompts.v3_1 import RETRIEVER_PROMPT as _BASE

__all__ = [
    "TRIAGE_PROMPT",
    "PREPROCESS_PROMPT",
    "RETRIEVER_PROMPT",
    "CALCULATOR_PROMPT",
]

RETRIEVER_PROMPT = (
    _BASE
    + """

## Targeted rules (v4, teacher-diagnosed)
- When turn_type is "number", return the value as printed in the source cell without any arithmetic or adjustment unless the instruction explicitly directs an operation; never estimate, subtract, or add values that are not captured verbatim from the table or text.
- When a question asks for a metric across multiple periods and the document presents that metric in year-indexed columns or per-year rows, map each sub-question to its own year's cell rather than reusing one period value; if the layout is ambiguous, flag the ambiguity instead of repeating a figure.
- When a sentence pairs an estimate or figure for one year against a value for another year, verify which year the question targets and return the value explicitly tied to that year, not the estimate, unless the report clearly labels it as the figure for the requested year.
"""
)
