"""Generated by convfinqa.evalloop.teacher — do not hand-edit.

Targeted challenger for v3_1: only the preprocess prompt changes.
Regenerate via `convfinqa-evalloop propose`.
"""

from convfinqa.prompts.v3_1 import (
    CALCULATOR_PROMPT,
    RETRIEVER_PROMPT,
    TRIAGE_PROMPT,
)
from convfinqa.prompts.v3_1 import PREPROCESS_PROMPT as _BASE

__all__ = [
    "TRIAGE_PROMPT",
    "PREPROCESS_PROMPT",
    "RETRIEVER_PROMPT",
    "CALCULATOR_PROMPT",
]

PREPROCESS_PROMPT = (
    _BASE
    + """

## Targeted rules (v5, teacher-diagnosed)
- For 'change from YEAR_A to YEAR_B' or 'net change from YEAR_A to YEAR_B', order operands as later-year (YEAR_B) minus earlier-year (YEAR_A) using the actual year labels, not word order, so an increase yields a positive result and a decrease yields a negative result.
- When a follow-up uses a bare anaphor (e.g., 'this total', 'this change', 'that stock', 'this amount'), bind it to the value and entity from the most recent preceding turn that plausibly matches, not to an earlier intermediate computed value or an older referent from a different subject.
- When a question asks which value was the highest/lowest (or otherwise requests identifying a max/min), emit a comparison program that returns the identified item, never a subtraction/difference program.
- When a follow-up asks for the 'total' of something broken into multiple component rows in prior turns, sum the previously established component values rather than reusing a single row's value.
- When a follow-up references an obfuscated or truncated token (e.g., '201d') tied to the same document, resolve it against the source's own row/column labels, preserve the prior metric phrasing, and flag ambiguity instead of inventing a year mapping; and when a follow-up asks for the 'maximum'/'minimum' of a metric whose prior answer was an implausibly small aggregate (e.g., 0), read the same series as the prior turn rather than the largest aggregate/ending-balance cell.
"""
)
