import type { ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { positionOf } from '../../app/nav';

/**
 * The header every page shares.
 *
 * Eyebrow: where this page sits in the story (`Evidence · 03 of 06`), read
 * from the nav so it cannot disagree with the rail. Title: the page's name at
 * the heading step. Verdict: the one sentence this page exists to state,
 * generated by the page from the same data it renders — never typed as a
 * constant, so it cannot go stale. Chips: identity and provenance on the right.
 */
export function PageHeader({
  title,
  verdict,
  chips,
  eyebrow,
  display = false,
  className,
}: {
  title: ReactNode;
  /** The sentence the page settles. `type-lede`, up to ~70ch. */
  verdict?: ReactNode;
  chips?: ReactNode;
  /** Overrides the nav-derived position when a page is not in the nav. */
  eyebrow?: string;
  /** Use the display step (landing, Architecture) instead of the heading step. */
  display?: boolean;
  className?: string;
}) {
  const { pathname } = useLocation();
  const position = eyebrow ?? positionOf(pathname) ?? '';

  return (
    <header
      data-testid="page-header"
      className={cn('flex min-w-0 flex-wrap items-start justify-between gap-x-6 gap-y-3', className)}
    >
      <div className="min-w-0 flex-1 basis-[36ch]">
        {position && <p className="mono-caps">{position}</p>}
        <h1 className={cn(display ? 'type-display' : 'type-h2', 'mt-1.5')}>{title}</h1>
        {verdict && (
          <div data-testid="page-verdict" className="type-lede mt-3 max-w-[70ch]">
            {verdict}
          </div>
        )}
      </div>
      {chips && (
        <div className="flex shrink-0 flex-wrap items-center gap-1.5 sm:justify-end">{chips}</div>
      )}
    </header>
  );
}
