"""The offline eval-regression gate. Runs on every pull request.

Because prediction CSVs are committed, the champion's accuracy can be re-scored
deterministically, with zero API calls and no key — which is the only reason a
gate like this can run on every PR at all. What it enforces:

    * the champion's committed accuracy has not fallen below its recorded floor
    * every version's CSV is still internally consistent (its `correct` column
      agrees with re-scoring its own answers against gold)
    * if a challenger is registered, it is compared to the champion and its
      pass->fail flips are printed

Exit code 1 fails the build. The output names the questions that broke, because
"accuracy dropped 0.4%" is not something anyone can act on.
"""

from __future__ import annotations

import sys

from convfinqa.evaluation import numeric_match
from convfinqa.tracking import registry
from convfinqa.tracking.comparator import (
    available_versions,
    compare,
    load_predictions,
)

# How far below its registered accuracy a version may drift before the gate
# fails. Zero would fail on float formatting alone; this is a hair of slack, not
# a licence to regress.
FLOOR_TOLERANCE = 0.005


def _rescore_consistency(version: str) -> tuple[int, int]:
    """Re-derive `correct` from answers and gold; return (n_rows, n_disagreements).

    Catches the failure mode where a CSV is edited or regenerated by hand and its
    correctness column stops describing its own contents — at which point every
    number downstream of it is fiction.
    """
    df = load_predictions(version)
    disagreements = 0
    for row in df.itertuples():
        recomputed = numeric_match(str(row.pred_answer), str(row.gold_answer))
        if bool(recomputed) != bool(row.correct):
            disagreements += 1
    return len(df), disagreements


def main(argv: list[str] | None = None) -> int:
    """Run the gate. Returns a process exit code."""
    del argv
    failures: list[str] = []
    versions = available_versions()

    if not versions:
        print("eval-gate: no committed prediction CSVs found — nothing to verify.")
        return 0

    print(f"eval-gate: {len(versions)} committed version(s): {', '.join(versions)}")

    # 1. Every CSV must describe itself correctly.
    for version in versions:
        n_rows, disagreements = _rescore_consistency(version)
        if disagreements:
            failures.append(
                f"{version}: {disagreements}/{n_rows} rows where the `correct` "
                "column disagrees with re-scoring the answer against gold"
            )
            print(f"  ✗ {version}: {disagreements}/{n_rows} inconsistent rows")
        else:
            print(f"  ✓ {version}: {n_rows} rows, correctness column consistent")

    # 2. The champion must not have fallen below its recorded floor.
    doc = registry.load()
    champion = doc.aliases.get(registry.CHAMPION)
    if champion is None:
        print("eval-gate: no champion registered yet — floor check skipped.")
    else:
        entry = registry.find_version(doc, champion) or {}
        recorded = float(entry.get("metrics", {}).get("accuracy", 0.0))
        try:
            current = float(load_predictions(champion)["correct"].mean())
        except (FileNotFoundError, ValueError) as exc:
            failures.append(f"champion {champion}: {exc}")
            current = 0.0
        floor = recorded - FLOOR_TOLERANCE
        status = "✓" if current >= floor else "✗"
        print(
            f"  {status} champion {champion}: {current:.2%} "
            f"(registered {recorded:.2%}, floor {floor:.2%})"
        )
        if current < floor:
            failures.append(
                f"champion {champion} accuracy {current:.2%} is below its "
                f"registered floor {floor:.2%}"
            )

    # 3. A registered challenger is compared to the champion.
    challenger = doc.aliases.get(registry.CHALLENGER)
    if champion and challenger and challenger != champion:
        result = compare(champion, challenger)
        print(f"\neval-gate: challenger {challenger} vs champion {champion}")
        print(f"  {result.reason()}")
        for flip in result.regressions[:20]:
            print(
                f"    pass→fail  {flip.report_id} q{flip.q_order}: "
                f"gold={flip.gold_answer!r} now={flip.candidate_answer!r}"
            )
        if len(result.regressions) > 20:
            print(f"    … and {len(result.regressions) - 20} more")
        if not result.promotable:
            print(
                "  (challenger is not promotable — this is information, not a failure)"
            )

    if failures:
        print("\neval-gate FAILED:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print("\neval-gate PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
