"""The offline eval-regression gate. Runs on every pull request.

Because prediction CSVs are committed, the champion's accuracy can be re-scored
deterministically, with zero API calls and no key — which is the only reason a
gate like this can run on every PR at all. What it enforces:

    * the champion's committed accuracy has not fallen below its recorded floor
    * every version's CSV is still internally consistent (its `correct` column
      agrees with re-scoring its own answers against gold)
    * if a challenger is registered, it is compared to the champion and its
      pass->fail flips are printed

The champion floor check branches on how the champion got there
(`registry` entry `source`). Legacy champions (`manual`/`gepa`/`s7`) are
re-scored from the full-corpus `pydantic_predictions_<version>.csv`. Champions
promoted through the evalloop/teacher path (`source == "evalloop"`, e.g. v5)
never get that file — their evidence is the test-split CSV the promotion
decision was actually made from, so they're re-scored from that instead (see
`comparator.load_evalloop_champion_predictions`).

Exit code 1 fails the build. The output names the questions that broke, because
"accuracy dropped 0.4%" is not something anyone can act on.
"""

from __future__ import annotations

import sys

import pandas as pd

from convfinqa.evaluation import numeric_match
from convfinqa.tracking import registry
from convfinqa.tracking.comparator import (
    available_versions,
    compare_frames,
    load_evalloop_champion_predictions,
    load_predictions,
)

# How far below its registered accuracy a version may drift before the gate
# fails. Zero would fail on float formatting alone; this is a hair of slack, not
# a licence to regress.
FLOOR_TOLERANCE = 0.005


def _rescore_consistency_df(df: pd.DataFrame) -> tuple[int, int]:
    """Re-derive `correct` from answers and gold; return (n_rows, n_disagreements).

    Catches the failure mode where a CSV is edited or regenerated by hand and its
    correctness column stops describing its own contents — at which point every
    number downstream of it is fiction.
    """
    disagreements = 0
    for row in df.itertuples():
        recomputed = numeric_match(str(row.pred_answer), str(row.gold_answer))
        if bool(recomputed) != bool(row.correct):
            disagreements += 1
    return len(df), disagreements


def _rescore_consistency(version: str) -> tuple[int, int]:
    return _rescore_consistency_df(load_predictions(version))


def _champion_predictions(champion: str, doc: registry.RegistryDoc) -> pd.DataFrame:
    """Load the champion's own evidence, from whichever path its `source` used."""
    entry = registry.find_version(doc, champion) or {}
    if entry.get("source") == "evalloop":
        return load_evalloop_champion_predictions(champion)
    return load_predictions(champion)


def main(argv: list[str] | None = None) -> int:
    """Run the gate. Returns a process exit code."""
    del argv
    failures: list[str] = []
    versions = available_versions()
    doc = registry.load()
    champion = doc.aliases.get(registry.CHAMPION)

    # Legacy CSVs and a registered champion are independent sources of work:
    # an evalloop-sourced champion (source == "evalloop") has no legacy CSV of
    # its own, so `versions` can be empty while there is still a champion to
    # floor-check — bailing out here on `versions` alone would silently skip it.
    if not versions and champion is None:
        print("eval-gate: no committed prediction CSVs found — nothing to verify.")
        return 0

    # 1. Every legacy full-corpus CSV must describe itself correctly.
    if versions:
        print(f"eval-gate: {len(versions)} committed version(s): {', '.join(versions)}")
        for version in versions:
            n_rows, disagreements = _rescore_consistency(version)
            if disagreements:
                failures.append(
                    f"{version}: {disagreements}/{n_rows} rows where the `correct` "
                    "column disagrees with re-scoring the answer against gold"
                )
                print(f"  ✗ {version}: {disagreements}/{n_rows} inconsistent rows")
            else:
                print(f"  ✓ {version}: {n_rows} rows, correctness column consistent")
    else:
        print("eval-gate: no legacy full-corpus CSVs committed.")

    # 2. The champion must not have fallen below its recorded floor.
    if champion is None:
        print("eval-gate: no champion registered yet — floor check skipped.")
    else:
        entry = registry.find_version(doc, champion) or {}
        recorded = float(entry.get("metrics", {}).get("accuracy", 0.0))
        try:
            champion_df = _champion_predictions(champion, doc)
        except (FileNotFoundError, ValueError) as exc:
            failures.append(f"champion {champion}: {exc}")
            current = 0.0
        else:
            n_rows, disagreements = _rescore_consistency_df(champion_df)
            if disagreements:
                failures.append(
                    f"champion {champion}: {disagreements}/{n_rows} rows where "
                    "the `correct` column disagrees with re-scoring the answer "
                    "against gold"
                )
            current = float(champion_df["correct"].mean())
        floor = recorded - FLOOR_TOLERANCE
        status = "✓" if current >= floor else "✗"
        print(
            f"  {status} champion {champion}: {current:.2%} "
            f"(registered {recorded:.2%}, floor {floor:.2%})"
        )
        if current < floor:
            failures.append(
                f"champion {champion} accuracy {current:.2%} is below its "
                f"registered floor {floor:.2%}"
            )

    # 3. A registered challenger is compared to the champion. The challenger
    #    alias is set by the legacy manual flow (`convfinqa-mlflow challenger`),
    #    so its own predictions always use the legacy load path; the champion
    #    side goes through `_champion_predictions` since it may be evalloop-sourced.
    challenger = doc.aliases.get(registry.CHALLENGER)
    if champion and challenger and challenger != champion:
        try:
            baseline_df = _champion_predictions(champion, doc)
            candidate_df = load_predictions(challenger)
        except (FileNotFoundError, ValueError) as exc:
            failures.append(f"challenger comparison {champion} vs {challenger}: {exc}")
            result = None
        else:
            result = compare_frames(
                baseline_df,
                candidate_df,
                baseline_version=champion,
                candidate_version=challenger,
            )
    else:
        result = None
    if result is not None:
        print(f"\neval-gate: challenger {challenger} vs champion {champion}")
        print(f"  {result.reason()}")
        for flip in result.regressions[:20]:
            print(
                f"    pass→fail  {flip.report_id} q{flip.q_order}: "
                f"gold={flip.gold_answer!r} now={flip.candidate_answer!r}"
            )
        if len(result.regressions) > 20:
            print(f"    … and {len(result.regressions) - 20} more")
        if not result.promotable:
            print(
                "  (challenger is not promotable — this is information, not a failure)"
            )

    if failures:
        print("\neval-gate FAILED:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print("\neval-gate PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
